@echo off

rem this file was generated by Jason

set PATH="C:\Program Files\Java\jdk1.5.0_05\bin";%PATH%

java -classpath ".;L:\Documents and Settings\frm05r\My Documents\workspace\JasonCVS\bin\jason.jar;L:\Documents and Settings\frm05r\My Documents\workspace\Argos;%CLASSPATH%" jason.infra.centralised.RunCentralisedMAS "L:\Documents and Settings\frm05r\My Documents\workspace\Argos\Argos.mas2j" 
