/**
 * 
 */
package org.soton.peleus.act.planner;

import jason.asSyntax.Literal;
import jason.asSyntax.Plan;

/**
 * A class representing the StripsPlan generated by an external planner
 * @author Felipe Meneguzzi
 *
 */
public abstract class StripsPlan extends ProblemTerms {
	
	/**
	 * Converts this StripsPlan into a non-generic AgentSpeak plan that is 
	 * activated by the introduction of a sequentially numbered term.
	 * @param planSequence The number term to associate to the plan's trigger.
	 * @return The resulting plan
	 */
	public abstract Plan toAgentSpeakPlan(int planSequence);
	
	/**
	 * Converts this StripsPlan into a generic AgentSpeak plan that is 
	 * activated in place of the planner whenever similar conditions arise in 
	 * the environment.
	 * @param triggerCondition The literal representing the trigger condition 
	 * 							for the activation of this plan
	 * @return The resulting plan
	 */
	public abstract Plan toGenericAgentSpeakPlan(Literal triggerCondition);
}
