/**
 * 
 */
package org.soton.peleus.mot;

import jason.asSyntax.Trigger;
import jason.bb.BeliefBase;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

/**
 * @author  Felipe Rech Meneguzzi
 */
public class Motivation {
	protected static final Logger logger = Logger.getLogger(Motivation.class.getName());
	/**
	 * The identifier for this motivation.
	 */
	protected final String motivationName;
	
	/**
	 * The current intensity for this motivation.
	 */
	protected int motivationIntensity;
	
	/**
	 * The threshold value after which goals will be generated by this motivation.
	 */
	protected int motivationThreshold;
	
	/**
	 * A strategy object to which the intensity update function is delegated.
	 */
	protected IntensityUpdateFunction intensityUpdateFunction;
	
	/**
	 * A strategy object to which the goal generation function is delegated.
	 */
	protected GoalGenerationFunction goalGenerationFunction;
	
	/**
	 * A stategy object to which the intention mitigation function is delegated.
	 */
	public MitigationFunction mitigationFunction;
	
	public static final List<Trigger> emptyList = new ArrayList<Trigger>(0);
	
	/**
	 * Creates a motivation with this name 
	 * @param motivationName
	 */
	Motivation(String motivationName) {
		this.motivationName = motivationName;
	}
	
	/**
	 * Creates a new motivation with a given name
	 * <code>IntensityUpdateFunction</code>,
	 * <code>GoalGenerationFunction</code>, and
	 * <code>MitigationFunction</code>.
	 * @param motivationName
	 * @param intensityUpdateFunction
	 * @param goalGenerationFunction
	 * @param mitigationFunction
	 */
	Motivation(String motivationName, 
			int threshold,
			IntensityUpdateFunction intensityUpdateFunction,
			GoalGenerationFunction goalGenerationFunction,
			MitigationFunction mitigationFunction) {
		this(motivationName);
		this.motivationThreshold = threshold;
		this.intensityUpdateFunction = intensityUpdateFunction;
		this.goalGenerationFunction = goalGenerationFunction;
		this.mitigationFunction = mitigationFunction;
	}

	/**
	 * @return  the motivationIntensity
	 * @uml.property  name="motivationIntensity"
	 */
	public int getMotivationIntensity() {
		return motivationIntensity;
	}

	/**
	 * @return  the motivationThreshold
	 * @uml.property  name="motivationThreshold"
	 */
	public int getMotivationThreshold() {
		return motivationThreshold;
	}

	/**
	 * @return  the motivationName
	 * @uml.property  name="motivationName"
	 */
	public String getMotivationName() {
		return motivationName;
	}

	/**
	 * Updates this motivation's intensity based on the current agent beliefs,
	 * and returns whether or not this motivations's threshold has been reached.
	 * 
	 * @param beliefBase A reference to the agent's <code>BeliefBase</code>
	 * @return Whether or not this motivation's threshold has been reached.
	 */
	public boolean updateIntensity(BeliefBase beliefBase) {
		this.motivationIntensity+=this.intensityUpdateFunction.updateIntensity(beliefBase);
		motivationIntensity = (motivationIntensity > 0) ? motivationIntensity : 0;
		logger.fine("Motivation '"+motivationName+"' intensity is "+motivationIntensity);
		return motivationIntensity >= motivationThreshold;
	}
	
	/**
	 * Generates the goals associated with this motivation.
	 * 
	 * @param beliefBase A reference to the agent's <code>BeliefBase</code>
	 * @return A list of new goals for the agent to accomplish 
	 * (Actually <code>Triggers</code>)
	 */
	public List<Trigger> generateGoals(BeliefBase beliefBase) {
		if(this.motivationIntensity >= motivationThreshold) {
			logger.info("Threshold exceeded, generating goals");
			return this.goalGenerationFunction.generateGoals(beliefBase);
		}
		return emptyList;
	}
	
	/**
	 * The function invoked when the goals associated with this motivation are 
	 * achieved.
	 * @param beliefBase A reference to the agent's <code>BeliefBase</code>
	 */
	public void mitigate(BeliefBase beliefBase) {
		//TODO Review the use of the mitigation function
		//The mitigation function should be applied differently
		this.motivationIntensity += this.mitigationFunction.mitigate(beliefBase);
		motivationIntensity = (motivationIntensity > 0) ? motivationIntensity : 0;
	}
	
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("Motivation ");
		sb.append(this.motivationName);
		sb.append("{");
		
		sb.append(System.getProperty("line.separator"));
		sb.append("   Intensity = ");
		sb.append(this.motivationIntensity);
		
		sb.append(System.getProperty("line.separator"));
		sb.append("   Threshold = ");
		sb.append(this.motivationThreshold);
		
		sb.append(System.getProperty("line.separator"));
		sb.append("   ");
		sb.append(this.intensityUpdateFunction.toString());
		
		sb.append(System.getProperty("line.separator"));
		sb.append("   ");
		sb.append(this.goalGenerationFunction.toString());
		
		sb.append(System.getProperty("line.separator"));
		sb.append("   ");
		sb.append(this.mitigationFunction.toString());
		
		sb.append(System.getProperty("line.separator"));
		sb.append("}");
		return sb.toString();
	}
}
